export const errors = {
    TITLE_NAME_IS_BLANK: 'TITLE_NAME_IS_BLANK',
    DESCRIPTION_NAME_IS_BLANK: 'DESCRIPTION_NAME_IS_BLANK',
    LEARNING_GOALS_IS_BLANK: 'LEARNING_GOALS_IS_BLANK',
    OVERVIEW_IS_BLANK: 'OVERVIEW_IS_BLANK',
    PRICE_IS_BLANK: 'PRICE_IS_BLANK',
    AUTHOR_IS_BLANK: 'AUTHOR_IS_BLANK',
};

//   module.exports = {
//     errors,
//   };
